language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

install:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo build -- --release &&
      travis-cargo test &&
      travis-cargo test -- --release &&
      travis-cargo bench &&
      travis-cargo --only stable doc

